name: Build
on:
  push:

jobs:
  build-and-analyse:
    name: Build & Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build Project
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lint
      - name: SonarQube Analyse
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SONARCLOUD_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ''
      - name: Upload lib
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: extension/lib

  #Â Although the gradle build can run in all environments, we exclude tasks to
  # build the Java lib to better mimic real-world situations, where the Java lib
  # is built & published using on one environment (linux).
  test-extension:
    needs: [build-and-analyse]
    name: 'Test Java ${{ matrix.java-version }} - Node ${{ matrix.node-version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        java-version: ['8', '11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Build Project
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build -x gradleTasksServerLib -x compileJava -x shadowJar -x startShadowScripts
      - name: Download lib
        uses: actions/download-artifact@v1
        with:
          name: lib
          path: extension/lib
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        if: matrix.os == 'ubuntu-latest'
      - name: Set permissions
        run: |
          chmod +x extension/lib/tasks-server
          unset npm_config_prefix
        if: matrix.os != 'windows-latest'
      - name: Test extension
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testVsCode -x gradleTasksServerLib -x compileJava -x shadowJar -x startShadowScripts
        env:
          DISPLAY: ':99.0'
          CI: 'true'
